version: '3.8'
services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=music-system
    volumes:
      - db:/var/lib/mysql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql #run data.sql when start
    ports:
      - "3307:3306"
    healthcheck:
      # api will wait for mysql to be ready - and complete the test
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - backend
  api:
    depends_on:
      mysqldb:
        condition: service_healthy # api will wait for mysql to be ready
    build: ./server
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - backend
      - frontend
    volumes:
      - ./server:/server
  ui:
    depends_on:
      - api
    build: ./client
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - backend
      - frontend
    volumes:
      - ./client:/client
volumes:
  db:
networks:
  backend:
  frontend:
